"""make company name unique

Revision ID: 77de4fd4579f
Revises: a1234a59b95c
Create Date: 2026-06-20 15:05:09.365987

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "77de4fd4579f"
down_revision: Union[str, Sequence[str], None] = "a1234a59b95c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_companies_name"), table_name="companies")
    op.create_unique_constraint("uq_companies_name", "companies", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_companies_name", "companies", type_="unique")
    op.create_index(op.f("ix_companies_name"), "companies", ["name"], unique=False)
    # ### end Alembic commands ###
