"""Add role column to company_members

Revision ID: 950601dcae52
Revises: ac3a22743e19
Create Date: 2026-06-17 20:59:53.280846

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "950601dcae52"
down_revision: Union[str, Sequence[str], None] = "ac3a22743e19"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    company_member_role = sa.Enum("OWNER", "ADMIN", "MEMBER", name="companymemberrole")
    company_member_role.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "company_members",
        sa.Column(
            "role",
            company_member_role,
            nullable=False,
            server_default="MEMBER",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("company_members", "role")
    sa.Enum(name="companymemberrole").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
